### PR TITLE
Add documentation using GitHub pages

### PR DESCRIPTION
**Pull request by ocrease**
@MindrustUK here is an initial PR to add documentation using github pages. You will need to configure pages, but that's easy to do. Go to https://github.com/MindrustUK/Heatmiser-for-home-assistant/settings/pages and point to the branch (dev?) once you've merged

### CODE REVIEW

**Comment by ocrease** [comment]
@MindrustUK I see you configured github pages, but I think it's not quite right. 

Source should be `Deploy from a branch`
Branch: `dev`
Folder: `/docs`

I suspect you have the folder set to `/ (root)`?

Here is the site URL https://mindrustuk.github.io/Heatmiser-for-home-assistant/

**Comment by ocrease** [comment]
FYI, once configured correctly, it should look a bit like this: https://ocrease.github.io/Heatmiser-for-home-assistant/

**Comment by MindrustUK** [comment]
Odd, this was working! I'll investigate.

**Comment by ocrease** [comment]
@MindrustUK The Gihub Pages config on my fork looks like this:

image

In case you want to compare

**Comment by MindrustUK** [comment]
Hmmm, strange behavior. I had this working as you demonstrated above. Then when visited this morning on your prompt I got a 404, on a refresh I got what I suspect what you were seeing; effectively the readme.md, re-deployed twice. Same thing, switched to root, deployed switched back to dev deployed and it seems right now.

Is it looking right your end @ocrease ?

**Comment by ocrease** [comment]
@MindrustUK yes it looks good at the moment. We will have to update the main readme file to include a link to the docs page and maybe clean up any duplicate details that are not needed in the readme anymore

**Comment by MindrustUK** [comment]
@ocrease Agreed, thinking the same.

**Pull request merged**
