### PR TITLE
Completely rewrite integration to use push

### PR DESCRIPTION
**Pull request by robcos**
Completely rewrite the integration using the _push_ methodology of fetching data with a _Coordinated, single API poll for data for all entities_ strategy as per https://developers.home-assistant.io/docs/integration_fetching_data

Fixes https://github.com/MindrustUK/Heatmiser-for-home-assistant/issues/77 and  https://github.com/MindrustUK/Heatmiser-for-home-assistant/issues/76

I know this is a big change so I would appreciate if anyone can pull it and try it

### CODE REVIEW

**Comment by MindrustUK** [comment]
I've got this in test at the minute, certainly my Neostat v1 isn't updating when setting temperature.

Only obvious error is:

```[1] Unexpected reply: namespace(cmdlist=['STORE_PROFILE', 'HOLIDAY', 'GET_LIVE_DATA', 'REMOVE_ZONE', 'GET_HOLD', 'SET_DELAY', 'SET_TIME', 'GET_PROFILE_0', 'SET_TEMP', 'GET_TEMPLOG', 'CANCEL_HOLIDAY', 'MANUAL_ON', 'GET_TIMER_0', 'CANCEL_HGROUP', 'REMOVE_REPEATER', 'GET_DEVICES', 'TIMER_HOLD_ON', 'CLEAR_OPEN_DELAY', 'SET_PUMP_DELAY', 'UNLOCK', 'READ_DCB', 'SET_COMFORT_LEVELS', 'ADVANCE', 'SET_LEVEL_4', 'GET_SYSTEM', 'SET_DIFF', 'RUN_PROFILE', 'BOOST_OFF', 'HOLD', 'DISABLE_MODE_CHANGE', 'SET_TIMECLOCK', 'RESET_HOMEKIT', 'NTP_ON', 'GET_GROUPS', 'SET_CLOSE_DELAY', 'COPY_DCB', 'SET_TEMP_FORMAT', 'GET_PROFILE', 'AWAY_OFF', 'GET_HOLIDAY', 'STORE_PROFILE_TIMER_0', 'SET_LEVEL_6', 'DST_OFF', 'CANCEL_HOLD_ALL', 'RESET', 'PROFILE_TITLE', 'DOWNLOAD_INSTALL', 'CLEAR_PROFILE_ID', 'ZONE_TITLE', 'NTP_OFF', 'GET_PROFILE_NAMES', 'TIMER_OFF', 'COOL_DEFAULT', 'ENGINEERS_DATA', 'IDENTIFY_DEV', 'MANUAL_OFF', 'SET_TIMER_FORMAT', 'CLEAR_CURRENT_PROFILE', 'CLEAR_PROFILE', 'SET_SWITCH_DELAY', 'TIMER_ON', 'WRITE_DCB', 'TIME_ZONE', 'GET_PROFILES', 'RESET_NCP', 'DELETE_GROUP', 'DST_ON', 'FROST_OFF', 'SET_FAILSAFE', 'TIMER_HOLD_OFF', 'FIRMWARE', 'LOCK', 'DETACH_DEVICE', 'USER_LIMIT', 'SET_RF_MODE', 'STORE_PROFILE_0', 'SET_CHANNEL', 'BOOST_ON', 'READ_TIMECLOCK', 'ALLOW_DOWNGRADE', 'FROST_ON', 'GET_DEVICE_LIST', 'STATISTICS', 'LINK_DEVICE', 'CLEAR_DEVICE_LIST', 'GLOBAL_DEV_LIST', 'IDENTIFY', 'SET_OPEN_DELAY', 'SET_TITLE', 'STORE_PROFILE2', 'SET_PREHEAT', 'SET_AUTO_ON', 'SUMMER_OFF', 'SET_FORMAT', 'VIEW_ROC', 'MANUAL_DST', 'AUTO_MODE_OFF', 'SUMMER_ON', 'OFFLINE_DEVICES', 'READ_COMFORT_LEVELS', 'CLEAR_CLOSE_DELAY', 'ULTRA_UPDATE_DONE', 'GET_ZONES', 'CREATE_GROUP', 'SET_DATE', 'AWAY_ON', 'SET_COOL_TEMP', 'GET_HOURSRUN', 'GET_PROFILE_TIMERS', 'RUN_PROFILE_ID', 'INFO', 'SET_FLOOR', 'GET_DATE', 'PERMIT_JOIN', 'SET_FROST', 'GET_ENGINEERS'])```

Haven't done any great digging but it looks like more work needed.

**Comment by robcos** [comment]
Do you have the logs?

**Comment by MindrustUK** [comment]
I'm afraid the excerpt above is the only thing appearing in the logs at the current log level. I'll bump the logging up and get back to you if there's anything more that comes out.

**Comment by robcos** [comment]
You should bump the logging level for neohubapi.neohub and we should be able to see what message is triggering the error.
We should fix the code though so that this is more apparent

**Comment by robcos** [comment]
@MindrustUK any chance you can get me the log level so we can move forward with this?
Thanks

**Comment by ribbal** [comment]
I've taken the changes that @robcos had made previously, and extended it to work (I believe).  @MindrustUK, would you be able to test?

There are still some further improvements I could make, but it would be good if these intermediate changes could be merged/tested incrementally first.

**Comment by ribbal** [comment]
The recent merge of PR (https://github.com/MindrustUK/Heatmiser-for-home-assistant/pull/88 - thanks to @robcos for doing the initial work) supersedes this PR.  @robcos, please could you close this and any associated issues?

**Comment by robcos** [comment]
Thank you @ribbal !

**Pull request closed without merging**
