### PR TITLE
Add target_temperature_step property

### PR DESCRIPTION
**Pull request by stikonas**
Heatmiser hardware can only use 1 degree increments (either C or F).

### CODE REVIEW

**Comment by DrTree** [comment]
On my setup at least the target temperature (via Heatmiser app) appears to go in 0.5C

**Comment by DrTree** [comment]
Yeah, I just checked my hardware devices - the neostat seems to be 1C when I adjust it but the neo air is 0.5C

**Comment by stikonas** [comment]
Oh, ok, then we might want to make this configurable.

**Comment by stikonas** [comment]
> Yeah, I just checked my hardware devices - the neostat seems to be 1C when I adjust it but the neo air is 0.5C

Actually, instead of configurable, probably best would be to detect what device it is and set it accordingly.

**Comment by ntompson** [comment]
My NeoStat does 0.5C steps. 

First bought out of the box they were 1C, but an automatic firmware upgrade to the NeoHub 6 months or so ago sent an update to the NeoStats which improved them to 0.5C.

**Comment by stikonas** [comment]
> My NeoStat does 0.5C steps.
> 
> First bought out of the box they were 1C, but an automatic firmware upgrade to the NeoHub 6 months or so ago sent an update to the NeoStats which improved them to 0.5C.

I see, I missed that because my NeoNub is disconnected from the network.

Then we can't rely even on device type.

Do you know if there is an API to detect step size? What firmware version do you have? (In case I find newer docs, the API documentation that I have does not mention it.)?

**Comment by ntompson** [comment]
Yeah I see your point. I just had a look at my iOS heatmiser app and found this in the faq:

https://faq.heatmiser.com/hc/en-us/articles/360013082959-0-5-Set-Point-Control-neoHub-Gen-2-

Seems like it was linked specifically to the neohub gen 2 and the update applied to both v1 and v2 of the neostats. So that's the background but not much info on how to detect.

**Comment by ntompson** [comment]
A couple of possibilities looking at the API... there's a firmware command:

```
FIRMWARE
{"FIRMWARE":0}

Possible results
{"firmware version":"<version>"}
```

Also a `VERSION_NUMBER` element in the `INFO` command. 

Maybe on of these might help.

**Comment by stikonas** [comment]
For now I have
`{"firmware version":"2128"}`
and
`'VERSION_NUMBER': 12`

**Comment by ntompson** [comment]
So I just did the same on mine and found:

```
{'FIRMWARE': 0} 
{"firmware version":"2135"} 
```

and

```
{'INFO': 0}
{... 'ULTRA_VERSION': 0, 'VERSION_NUMBER': 24, ...}
```

Happy to provide the entire `INFO` dump if that's helpful.

**Comment by stikonas** [comment]
Ok, so there is some range of VERSION_NUMBERS and firmware versions between our devices... Maybe I should write to support@heatmiser.com and see if they can be helpful.

**Comment by stikonas** [comment]
Ok, I've got a reply from heatmiser. There is no specific command to return degree step, it's just based on firmware version (need at least v2135). I've also got a sligthly newer API docs from them (version 2.8)

**Comment by ntompson** [comment]
That's great - I'd love to see the version 2.8 API doc, if you are able to share.

**Comment by andriuss-xilinx** [comment]
> That's great - I'd love to see the version 2.8 API doc, if you are able to share.

https://nextcloud.stikonas.eu/s/wn9eJ4bte8aMdFc

**Comment by ntompson** [comment]
Awesome!

**Comment by stikonas** [comment]
Sorry, this is not ready for merge yet.

**Comment by ribbal** [comment]
Here are my thoughts and findings on this issue:

- my stats only allow 1 degree step increments (hardware limitation, I guess)
- my heatmiser app allows 0.5 step increments (following a firmware/software update some time ago IIRC)
- I updated the home assistant integration to allow 0.1 degree increments (hardcoded), and found that the stats honoured the 0.1 step increments (which suggests that the stats/hardware will work with any temperature step increments)

From reading through the comments above, my understanding is that we are trying to limit the home assistant integration to support either 1 degree or 0.5 degree temperature step increments (based on hardware/firmware versions).  The default increment is 0.5 in the home assistant integration, so I would ask why would anyone want to limit this to 1 degree when 0.5 provides additional options?

My installation consists of the original neoStats (when they were first released) and a v2 hub, so other installations may have different experiences to me.  However, when the default home assistant increment is 0.5, why would this need to be limited to 1 degree?

**Comment by stikonas** [comment]
> Here are my thoughts and findings on this issue:
> 
>     * my stats only allow 1 degree step increments (hardware limitation, I guess)
> 
>     * my heatmiser app allows 0.5 step increments (following a firmware/software update some time ago IIRC)
> 
>     * I updated the home assistant integration to allow 0.1 degree increments (hardcoded), and found that the stats honoured the 0.1 step increments (which suggests that the stats/hardware will work with any temperature step increments)
> 
> 
> From reading through the comments above, my understanding is that we are trying to limit the home assistant integration to support either 1 degree or 0.5 degree temperature step increments (based on hardware/firmware versions). The default increment is 0.5 in home assistant, so I would ask why would anyone want to limit this to 1 degree when 0.5 provides additional options?
> 
> My installation consists of the original neoStats (when they were first released) and a v2 hub, so other installations may have different experiences to me. However, when the default home assistant increment is 0.5, why would you want to limit it to 1 degree?
> 
> I hope I understood the issue correctly (I may be lucky because I have a v2 hub).

Heatmiser told us that hubs running v2135 or later support .5 set temperatures but older ones support 1 degree set temperatures. That was my impression from testing too. Trying to set smaller increment on older firmware resulted in hardware not honouring it and eventually home assistant would jump back to integer temperature.

Maybe even newer firmware is required to support 0.1 degree set increments? I haven't heard anything about that though.

**Comment by ribbal** [comment]
Hi @stikonas, thanks for the clarification.

You are probably correct that most installations will be on the latest firmware version.  However, I guess we still need to support v1 hubs.

I think this PR (https://github.com/MindrustUK/Heatmiser-for-home-assistant/pull/91) may fix the temperature step issue.

**Pull request closed without merging**
