### PR TITLE
Increment neohubapi version : To fix repeater name

### PR DESCRIPTION
**Pull request by ribbal**

### CODE REVIEW

**Comment by stikonas** [comment]
Please don't merge it yet. I need to make an actual release and upload it to PyPI.

**Comment by stikonas** [comment]
0.9 was now pushed to PyPI:

https://pypi.org/project/neohubapi/0.9/

**Comment by ribbal** [comment]
Thanks.  And, apologies for jumping the gun with this PR.

**Comment by Trouble-51** [comment]
Hi All,

Is there any chance of getting the ‘hold’ functionality included in the integration? I guess this would require the help of Heatmiser changing the api? If possible it would be very much appreciated. It would give my significant other the possibility to increase the temperature for a set period 

Thanks!

**Comment by ribbal** [comment]
@Trouble-51, there is already an issue raised for this: https://github.com/MindrustUK/Heatmiser-for-home-assistant/issues/9

**Comment by ribbal** [comment]
> Hi All, Is there any chance of getting the ‘hold’ functionality included in the integration? I guess this would require the help of Heatmiser changing the api? If possible it would be very much appreciated. It would give my significant other the possibility to increase the temperature for a set period Thanks!
> […](#)
@Trouble-51, there is already an issue raised for this: #9

**Pull request merged**
