### PR TITLE
Add battery status based on other branch's work

### PR DESCRIPTION
**Pull request by cyclops1982**
Hi,

This adds support for battery status and an offline sensor. The work was done by @lynchdonaia and i've updated it to provide some better support.
Unfortunatly, HA requires the battery status to be in percentages, so it's faked by 100% (normal), 10% (if battery indicator is shown) or 0% (when offline).

### CODE REVIEW

**Comment by MindrustUK** [comment]
Thanks for the work, going to merge this and do a smoke test.

**Comment by MindrustUK** [comment]
Looks like this is all broadly working as intended.

Immediate testing flags up that if a device is offline; example: I have a neoStat-e V2 turned off at the breaker at the minute. That the battery level and network connectivity values aren't populated.

The device also appears as a switch rather than a Thermostat, this behaviour I believe feeds into the way the neohub library works and will be addressed as part of: https://github.com/MindrustUK/Heatmiser-for-home-assistant/issues/121 where device states are returned form 'latest data' rather than listing devices and types (which from memory I think comes from 'info'.

Also, for wired devices I'm not sure we should be necessarily returning battery level. Something that can be addressed once the device typing is more robust.

Once again thanks for the contribution.

**Comment by cyclops1982** [comment]
Thanks for merging this!

I only have wireless devices. Would love to help update the code if i had a device. Is there any chance heatmiser can help with that?

**Comment by MindrustUK** [comment]
Hi @cyclops1982 I've not had hardware from Heatmiser for development, but you can try your luck on the developer portal here: https://dev.heatmiser.com/

**Comment by lynchdonala** [comment]
Nice @cyclops1982 :+1: 

On the NTP re-enabling workaround: I had opened a support ticket with Heatmiser back towards the end of 2019, but it basically ended with them saying that they see no issue with the NTP client on the NeoHub, thus the workaround that I applied. 

This is a PDF of the ticket with Heatmiser, which includes the behaviour I was seeing with the NeoHub:
[Neo Hub Gen 2 - Date & Time incorrect after power cut_outage – Heatmiser FAQ.pdf](https://github.com/MindrustUK/Heatmiser-for-home-assistant/files/11412520/Neo.Hub.Gen.2.-.Date.Time.incorrect.after.power.cut_outage.Heatmiser.FAQ.pdf)

**Comment by cyclops1982** [comment]
Hey @lynchdonala  - most work was yours, so thanks for getting it started!

Thanks for the PDF output of the support ticket. I haven't noticed the NTP problem but i'm sure it exists. I am not running my own NTP on the network - no clue what the hub would take by default and how well it works. Might be worth a pcap :)

**Pull request merged**
