### PR TITLE
Add option to manually configure HVAC modes

### PR DESCRIPTION
**Pull request by ribbal**

### CODE REVIEW

**Comment by ribbal** [comment]
@MindrustUK, I am unable to update to the latest version.  This is what I get in the logs:

image

...and, the Heatmiser Neo doesn't appear in the list of integrations?  Are you able to have a look, please?

**Comment by MindrustUK** [comment]
@ribbal I've reverted it for now until I have a chance to investigate (to save the upstream users breaking).

**Comment by ribbal** [comment]
Also, when installing the previous version to this one (which I did this morning), it appeared to install the files in a **/heatmiserneo/heatmisterneo** folder (duplicate folder structure):

image

**Comment by ribbal** [comment]
@MindrustUK, I think this may have been an issue a=t my end.  The database appeared to be corrupt; I deleted it, re-dowloaded the heatmiser integration, and installed it.  It now works, and is just waiting on the release of the latest changes.  I can re-test the update, once it's ready from your end?

**Comment by MindrustUK** [comment]
Hi @ribbal Just reverted my revert of your previous pull ;) I.e. the latest code should now be there. I've pulled it down and updated my local instance. Looks like everything is good here! Apologies for the delay in investigating work is keeping me busy.

**Comment by ribbal** [comment]
@MindrustUK, that's great; thanks.

I updated again, and still have the same problem; it's installing to the custom_components/**heatmiserneo/heatmiserneo** sub-folder.

I removed the integration, deleted all files, re-downloaded and installed the integration from scratch (with multiple restarts).  It works for now.  Not sure what will happen if I upgrade again.  I'll keep my eye on it.  If you have any ideas, that would be great.

Apologies for dragging you into something that appears to only affect me (never had this problem before, when upgrading the heatmiser Neo integration).  It's working for now.

**Comment by Trouble-51** [comment]
I have the same issue, when updating via HACS and restarting there are two heatmiserneo directories, one inside the other. When moving the files in the second one to the first one and restarting HA it works

 

Jos

 

From: ribbal ***@***.***>
Reply to: MindrustUK/Heatmiser-for-home-assistant ***@***.***>
Date: Tuesday, 11 January 2022 at 12:08
To: MindrustUK/Heatmiser-for-home-assistant ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [MindrustUK/Heatmiser-for-home-assistant] Add option to manually configure HVAC modes (PR #103)

 

@MindrustUK, that's great; thanks.

I updated again, and still have the same problem; it's installing to the custom_components/heatmiserneo/heatmiserneo sub-folder.

I removed the integration, deleted all files, re-downloaded and installed the integration from scratch (with multiple restarts). It works for now. Not sure what will happen if I upgrade again. I'll keep my eye on it. If you have any ideas, that would be great.

Apologies for dragging you into something that appears to only affect me (never had this problem before, when upgrading the heatmiser Neo integration). It's working for now.

**Pull request merged**
